---
- name: Playbook 1
  # Uses generic PACKAGE module to install/remove packages, FIREWALLD to manage firewall rules,
  # SERVICE module to restart services and COPY module to create a new file with content (module supports this)
  user: ansible

  tasks:
  - name: Install Apache
    package:
      name: httpd
      state: latest

  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started

  - name: Enable service httpd
    service:
      name: httpd
      enabled: yes

  - name: Creating a file /var/www/html/index.html
    copy:
      dest: /var/www/html/index.html
      content: |
        Welcome to my web server

  - name: Open HTTP on firewall
    firewalld:
      service: http
      permanent: yes
      state: enabled

  - name: Open HTTPS on firewall
    firewalld:
      service: https
      permanent: yes
      state: enabled

  - name: Restart service firewalld
    service:
      name: firewalld.service
      state: restarted
